### ISSUE TITLE
Bicubic interpolation method for depth resizing

### ISSUE THREAD

**Issue by koutilya-pnvr** [lyndonzheng/Synthetic2Realistic#32]
https://github.com/lyndonzheng/Synthetic2Realistic/blob/f06db4734b89f80b76f9362ddec17f8eaf1216db/dataloader/data_loader.py#L49

The Bicubic interpolation is messing up the min and max values of the depth images, although the mean remains to be fairly intact. Moreover, Bilinear interpolation seems to respect the range and keeps the min and max values the same. Any reason to chose the Bicubic interpolation for depth images in particular?

**Comment by lyndonzheng** [comment]
@koutilya40192 We try the BICUBIC and BILINEAR for the training Because this interpolation gives better results in our experiments, then we use it. Like the rotation function, we try bilinear and bicubic function, and chose it based on the experiment results. In the testing, to ensure the min and max range, we follow the pervious work that uses bilinear interpolation for predicted and ground truth depth.

**Comment by koutilya-pnvr** [comment]
So you were using Bicubic during training and Bilinear during testing based on empirical results?

**Comment by lyndonzheng** [comment]
@koutilya40192 Bilinear is used for the evaluation. This design just base on the results.

**Comment by koutilya-pnvr** [comment]
I see. Thanks for your response.
